[versions]
agp = "8.11.2"
kotlin = "2.2.0"
coreKtx = "1.17.0"
junit = "4.13.2"

hiltAndroid = "2.57.2"
daggerhiltcompiler="2.57.2"
kotlinKsp = "2.2.0-2.0.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
activityKtx = "1.11.0"
fragmentKtxVersion = "1.8.9"
navigation = "2.9.6"
lottie = "6.7.1"

constraintlayout = "2.2.1"

kotlinxCoroutinesCore = "1.10.2"
lifecycleViewmodelKtx = "2.9.1"
lifecycleLivedataKtx = "2.9.1"
okhttp = "5.0.0"
retrofit = "3.0.0"
converter-gson="3.0.0"
dataStoreVersion="1.1.7"
chuckerVersion="4.1.0"
facebookShimmer="0.5.0"
swiperefreshlayout = "1.1.0"
coil="3.3.0"

roomRuntime = "2.8.3"
gsonVersion="2.13.2"
glideVersion="4.16.0"
dfmFragment="2.9.6"
featureDelivery="2.1.0"
pagingRuntimeKtxVersion = "3.3.6"
navigationDynamicFeaturesRuntime = "2.9.6"
preference = "1.2.0"
coreTesting = "2.2.0"
kotlinxCoroutinesTest = "1.10.2"
leakcanaryAndroid = "3.0-alpha-8"
androidDatabaseSqlcipher = "4.5.4"
sqliteKtx = "2.6.2"
junitKtx = "1.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }

androidx-navigation-dynamic-features-fragment={module="androidx.navigation:navigation-dynamic-features-fragment",version.ref="dfmFragment"}

gms-play-services-base={ module = "com.google.android.play:feature-delivery", version.ref = "featureDelivery" }
gms-play-services-base-ktx={ module = "com.google.android.play:feature-delivery-ktx", version.ref = "featureDelivery" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStoreVersion" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
facebook-shimmer={ module = "com.facebook.shimmer:shimmer", version.ref = "facebookShimmer" }
gson ={ module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
glide ={ module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }



chucker-library ={module = "com.github.chuckerteam.chucker:library",version.ref="chuckerVersion"}
chucker-no-op ={module = "com.github.chuckerteam.chucker:library-no-op",version.ref="chuckerVersion"}

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerhiltcompiler" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerhiltcompiler" }

converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

coil3-coil= { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil3-okhttp= { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtxVersion" }

androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomRuntime" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "pagingRuntimeKtxVersion" }

androidx-navigation-dynamic-features-runtime = { group = "androidx.navigation", name = "navigation-dynamic-features-runtime", version.ref = "navigationDynamicFeaturesRuntime" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTesting" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanaryAndroid" }
android-database-sqlcipher = { group = "net.zetetic", name = "android-database-sqlcipher", version.ref = "androidDatabaseSqlcipher" }
androidx-sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqliteKtx" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp =  { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
daggerhilt ={id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
